### ISSUE TITLE
Cloned version not working

### ISSUE THREAD

**Issue by mattbag** [storyblok/fieldtype-tinymce#1]
Hello, just wondering why a copy paste of your production code,
as well as a fresh build of the repo, are not working as a new plugin, with a new plugin id/name.
I am running the localhost preview of the space, the default one works very well, but not the cloned.

Also i think in the docs there's a mistake/typo. At the 5th step it says to paste in the content of src/vendor/export, while it should be dist/export
https://www.storyblok.com/docs/Guides/Creating-a-field-type-plugin
It is correct on the plugin github page.

Am I missing a step?
I doesn't really show what to do after pasting in, I assumed save and publish. But the content type in the editor is blank.
Thanks!

**Comment by ademarCardoso** [comment]
Hi @mattbag thanks to submit this issue, and I'm sorry for the delay in responding. First of all, do you still have this problem?

**Comment by mattbag** [comment]
Honestly I don't remember, I tried several other ways and at some point I made my own editor. I think there have been many improvement on the core components in storyblok so you can close the issue
